#!/bin/bash -e

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

usage() {
  cat <<END
Usage: $progname OPTIONS
  -h            Display this help text
  -p            Specify listen port

${*:-}
END
  exit 1
}

while getopts "hp:" OPTION ; do
  case $OPTION in
    h)
      usage
      ;;
    p)
      port=$OPTARG
      ;;
    *)
      usage
      ;;
  esac
done

port=${port:-64738}

docker run --restart=always -d -v $DIR/../data:/data -p $port:64738/tcp -p $port:64738/udp murmur
