#!/bin/bash -e

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

usage() {
  cat <<END
Usage: $progname OPTIONS
  -h            Display this help text
  -p            Specify listen port

${*:-}
END
  exit 1
}

while getopts "hp:i" OPTION ; do
  case $OPTION in
    h)
      usage
      ;;
    p)
      port=$OPTARG
      ;;
    i)
      interactive=true
      ;;
    *)
      usage
      ;;
  esac
done

port=${port:-64738}

if [ $interactive ]; then
  docker run -t -i -v $DIR/../data:/data -p $port:64738/tcp -p $port:64738/udp murmur /bin/bash
else
  docker run -d -v $DIR/../data:/data -p $port:64738/tcp -p $port:64738/udp murmur
fi
